name: 'Deploy'
author: 'nicholas@nicholasodonnell.com'
description: 'Deploy REPL'
branding:
  icon: 'globe'
  color: 'green'
inputs:
  access-token:
    description: 'GitHub access token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.access-token }}
